
title: My Resume
url: 'http://gilleslasnier.com'
baseurl: '/online-cv' #change it according to your repository name

#Profile information
name: Gilles Lasnier
tagline: Head of Research &amp Development
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: 1st.last@gmail.com
phone: +33 6 7X XX XX XX
website: gilleslasnier.com #do not add http://
linkedin: glasnier
github: glasnier
twitter: '@gilleslasnier'

#Update all the sections by editing the files inside _includes folder.
